import { useEffect, useState } from "react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { getMarketplaceListingsForAdmin, getMarketplaceReportsForAdmin, updateMarketplaceListingStatus, updateMarketplaceReportStatus } from "@/services/marketplace";
import type { MarketplaceListing, MarketplaceReport } from "@/types/database";

export default function MarketplaceAdminTab() {
  const [listings, setListings] = useState<MarketplaceListing[]>([]);
  const [reports, setReports] = useState<MarketplaceReport[]>([]);
  const [loading, setLoading] = useState(true);
  const load = async () => { const [nextListings, nextReports] = await Promise.all([getMarketplaceListingsForAdmin().catch(() => []), getMarketplaceReportsForAdmin().catch(() => [])]); setListings(nextListings); setReports(nextReports); setLoading(false); };
  const refresh = async () => { setLoading(true); await load(); };
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, []);
  const changeListingStatus = async (id: string, status: MarketplaceListing["status"]) => { const result = await updateMarketplaceListingStatus(id, status); if (result.ok) setListings((items) => items.map((item) => item.id === id ? { ...item, status } : item)); };
  const changeReportStatus = async (id: string, status: MarketplaceReport["status"]) => { const result = await updateMarketplaceReportStatus(id, status); if (result.ok) setReports((items) => items.map((item) => item.id === id ? { ...item, status } : item)); };
  return <div className="space-y-6"><div className="flex items-center justify-between gap-3"><div><h2 className="text-2xl font-bold">Marketplace</h2><p className="mt-1 text-sm text-muted-foreground">Modere anúncios e denúncias da comunidade.</p></div><Button variant="outline" onClick={() => void refresh()} disabled={loading}>Atualizar</Button></div><Card className="overflow-hidden"><div className="border-b border-border p-4 font-semibold">Anúncios ({listings.length})</div>{loading ? <div className="p-6 text-center text-muted-foreground">Carregando...</div> : <div className="divide-y divide-border">{listings.map((listing) => <div key={listing.id} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">{listing.title}</p><p className="text-sm text-muted-foreground">{listing.city} · {listing.owner_name || "Usuário"}</p><Badge variant="secondary" className="mt-1">{listing.status}</Badge></div><div className="flex gap-2">{listing.status !== "removed" ? <Button size="sm" variant="outline" onClick={() => void changeListingStatus(listing.id, "removed")}>Remover</Button> : <Button size="sm" variant="outline" onClick={() => void changeListingStatus(listing.id, "active")}>Restaurar</Button>}</div></div>)}</div>}</Card><Card className="overflow-hidden"><div className="border-b border-border p-4 font-semibold">Denúncias ({reports.length})</div>{reports.length === 0 ? <div className="p-6 text-center text-muted-foreground">Nenhuma denúncia registrada.</div> : <div className="divide-y divide-border">{reports.map((report) => <div key={report.id} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">{report.listing?.title || "Anúncio"}</p><p className="text-sm text-muted-foreground">{report.reason}{report.details ? ` · ${report.details}` : ""}</p><Badge variant="secondary" className="mt-1">{report.status}</Badge></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => void changeReportStatus(report.id, "reviewing")}>Analisar</Button><Button size="sm" onClick={() => void changeReportStatus(report.id, "resolved")}>Resolver</Button></div></div>)}</div>}</Card></div>;
}
