// Shared by directory pages and sitemap generation. Slugs are permanent URL identifiers.
export const DIRECTORY_CATEGORY_MINIMUM_BUSINESSES = 3;

export const DIRECTORY_CATEGORIES = [
  { categoryId: "restaurant", slug: "restaurantes-brasileiros", label: "Restaurantes brasileiros" },
  { categoryId: "pizzeria", slug: "pizzarias-brasileiras", label: "Pizzarias brasileiras" },
  { categoryId: "churrascaria", slug: "churrascarias-brasileiras", label: "Churrascarias brasileiras" },
  { categoryId: "bakery", slug: "padarias-brasileiras", label: "Padarias brasileiras" },
  { categoryId: "confectionery", slug: "confeitarias-brasileiras", label: "Confeitarias brasileiras" },
  { categoryId: "bar", slug: "bares-brasileiros", label: "Bares brasileiros" },
  { categoryId: "cafe", slug: "cafes-brasileiros", label: "Caf\u00e9s brasileiros" },
  { categoryId: "mechanic", slug: "oficinas-mecanicas-brasileiras", label: "Oficinas mec\u00e2nicas brasileiras" },
  { categoryId: "body_shop", slug: "funilarias-e-pinturas-brasileiras", label: "Funilarias e pinturas brasileiras" },
  { categoryId: "tires", slug: "borracharias-brasileiras", label: "Borracharias brasileiras" },
  { categoryId: "auto_electric", slug: "autoeletricas-brasileiras", label: "Autoel\u00e9tricas brasileiras" },
  { categoryId: "car_wash", slug: "lava-cars-brasileiros", label: "Lava-cars brasileiros" },
  { categoryId: "towing", slug: "guinchos-brasileiros", label: "Guinchos brasileiros" },
  { categoryId: "dealership", slug: "concessionarias-brasileiras", label: "Concession\u00e1rias brasileiras" },
  { categoryId: "car_dealership", slug: "revendas-de-carros-brasileiras", label: "Revendas de carros brasileiras" },
  { categoryId: "automotive_center", slug: "centros-automotivos-brasileiros", label: "Centros automotivos brasileiros" },
  { categoryId: "medical_clinic", slug: "clinicas-brasileiras", label: "Cl\u00ednicas brasileiras" },
  { categoryId: "doctor", slug: "medicos-brasileiros", label: "M\u00e9dicos brasileiros" },
  { categoryId: "pediatrician", slug: "pediatras-brasileiros", label: "Pediatras brasileiros" },
  { categoryId: "dentist", slug: "dentistas-brasileiros", label: "Dentistas brasileiros" },
  { categoryId: "manicure", slug: "manicures-brasileiras", label: "Manicures brasileiras" },
  { categoryId: "hairdresser", slug: "cabeleireiros-brasileiros", label: "Cabeleireiros brasileiros" },
  { categoryId: "beauty_salon", slug: "saloes-de-beleza-brasileiros", label: "Sal\u00f5es de beleza brasileiros" },
  { categoryId: "barbershop", slug: "barbearias-brasileiras", label: "Barbearias brasileiras" },
  { categoryId: "personal_trainer", slug: "personal-trainers-brasileiros", label: "Personal trainers brasileiros" },
  { categoryId: "construction_company", slug: "construtoras-brasileiras", label: "Construtoras brasileiras" },
  { categoryId: "electrician", slug: "eletricistas-brasileiros", label: "Eletricistas brasileiros" },
  { categoryId: "plumber", slug: "encanadores-brasileiros", label: "Encanadores brasileiros" },
  { categoryId: "painter", slug: "pintores-brasileiros", label: "Pintores brasileiros" },
  { categoryId: "lawyer", slug: "advogados-brasileiros", label: "Advogados brasileiros" },
  { categoryId: "translator", slug: "tradutores-brasileiros", label: "Tradutores brasileiros" },
  { categoryId: "immigration_consultant", slug: "consultorias-de-imigracao", label: "Consultorias de imigra\u00e7\u00e3o" },
  { categoryId: "accountant", slug: "contadores-brasileiros", label: "Contadores brasileiros" },
  { categoryId: "financial_advisor", slug: "consultores-financeiros-brasileiros", label: "Consultores financeiros brasileiros" },
  { categoryId: "insurance_broker", slug: "corretores-de-seguros-brasileiros", label: "Corretores de seguros brasileiros" },
  { categoryId: "remittance", slug: "cambio-e-remessas", label: "C\u00e2mbio e remessas" },
  { categoryId: "teacher", slug: "professores-brasileiros", label: "Professores brasileiros" },
  { categoryId: "english_teacher", slug: "professores-de-ingles-brasileiros", label: "Professores de ingl\u00eas brasileiros" },
  { categoryId: "driving_school", slug: "autoescolas-brasileiras", label: "Autoescolas brasileiras" },
  { categoryId: "school", slug: "escolas-brasileiras", label: "Escolas brasileiras" },
  { categoryId: "supermarket", slug: "supermercados-brasileiros", label: "Supermercados brasileiros" },
  { categoryId: "retail_market", slug: "mercados-brasileiros", label: "Mercados brasileiros" },
  { categoryId: "brazilian_store", slug: "produtos-brasileiros", label: "Produtos brasileiros" },
  { categoryId: "clothing_store", slug: "lojas-de-roupas-brasileiras", label: "Lojas de roupas brasileiras" },
  { categoryId: "moving_company", slug: "empresas-de-mudanca-brasileiras", label: "Empresas de mudan\u00e7a brasileiras" },
  { categoryId: "freight_logistics", slug: "fretes-brasileiros", label: "Fretes brasileiros" },
  { categoryId: "passenger_transport", slug: "transporte-de-passageiros", label: "Transporte de passageiros" },
  { categoryId: "van_service", slug: "servicos-de-van-brasileiros", label: "Servi\u00e7os de van brasileiros" },
  { categoryId: "cat_boarding", slug: "hospedagem-para-gatos", label: "Hospedagem para gatos" },
  { categoryId: "dog_boarding", slug: "hospedagem-para-caes", label: "Hospedagem para c\u00e3es" },
  { categoryId: "grooming", slug: "banho-e-tosa-brasileiros", label: "Banho e tosa brasileiros" },
  { categoryId: "veterinary", slug: "clinicas-veterinarias-brasileiras", label: "Cl\u00ednicas veterin\u00e1rias brasileiras" },
  { categoryId: "veterinarian", slug: "veterinarios-brasileiros", label: "Veterin\u00e1rios brasileiros" },
  { categoryId: "pet_training", slug: "adestradores-brasileiros", label: "Adestradores brasileiros" },
  { categoryId: "dog_walker", slug: "passeadores-de-caes-brasileiros", label: "Passeadores de c\u00e3es brasileiros" },
  { categoryId: "pet_shop", slug: "pet-shops-brasileiros", label: "Pet shops brasileiros" },
  { categoryId: "daycare", slug: "creches-infantis-brasileiras", label: "Creches infantis brasileiras" },
  { categoryId: "babysitter", slug: "babas-brasileiras", label: "Bab\u00e1s brasileiras" },
  { categoryId: "elderly_caregiver", slug: "cuidadores-de-idosos-brasileiros", label: "Cuidadores de idosos brasileiros" },
  { categoryId: "nurse", slug: "enfermeiros-brasileiros", label: "Enfermeiros brasileiros" },
  { categoryId: "home_care", slug: "assistencia-domiciliar-brasileira", label: "Assist\u00eancia domiciliar brasileira" },
  { categoryId: "diarist", slug: "diaristas-brasileiras", label: "Diaristas brasileiras" },
  { categoryId: "home_cleaning", slug: "limpeza-residencial-brasileira", label: "Servi\u00e7os de limpeza residencial brasileiros" },
  { categoryId: "real_estate_agency", slug: "imobiliarias-brasileiras", label: "Imobili\u00e1rias brasileiras" },
  { categoryId: "realtor", slug: "corretores-de-imoveis-brasileiros", label: "Corretores de im\u00f3veis brasileiros" },
  { categoryId: "property_management", slug: "administracao-de-imoveis", label: "Administra\u00e7\u00e3o de im\u00f3veis" },
  { categoryId: "travel_agency", slug: "agencias-de-turismo-brasileiras", label: "Ag\u00eancias de turismo brasileiras" },
  { categoryId: "tour_guide", slug: "guias-de-turismo-brasileiros", label: "Guias de turismo brasileiros" },
  { categoryId: "tours", slug: "passeios-e-excursoes", label: "Passeios e excurs\u00f5es" },
  { categoryId: "travel_insurance", slug: "seguro-viagem", label: "Seguro viagem" },
  { categoryId: "accommodation", slug: "hospedagens-brasileiras", label: "Hospedagens brasileiras" },
  { categoryId: "hotel", slug: "hoteis-brasileiros", label: "Hot\u00e9is brasileiros" },
  { categoryId: "rock_band", slug: "bandas-de-rock-brasileiras", label: "Bandas de rock brasileiras" },
  { categoryId: "forro_band", slug: "bandas-de-forro-brasileiras", label: "Bandas de forr\u00f3 brasileiras" },
  { categoryId: "chorinho", slug: "chorinho-brasileiro", label: "Chorinho brasileiro" },
  { categoryId: "samba", slug: "samba-brasileiro", label: "Samba brasileiro" },
  { categoryId: "funk", slug: "funk-brasileiro", label: "Funk brasileiro" },
  { categoryId: "pagode_group", slug: "grupos-de-pagode-brasileiros", label: "Grupos de pagode brasileiros" },
  { categoryId: "sertanejo", slug: "sertanejo-brasileiro", label: "Sertanejo brasileiro" },
  { categoryId: "choir", slug: "coros-brasileiros", label: "Coros brasileiros" },
  { categoryId: "musician", slug: "musicos-brasileiros", label: "M\u00fasicos brasileiros" },
  { categoryId: "music", slug: "musica-brasileira", label: "M\u00fasica brasileira" },
  { categoryId: "musicista", slug: "musicistas-brasileiros", label: "Musicistas brasileiros" },
  { categoryId: "dj", slug: "djs-brasileiros", label: "DJs brasileiros" },
  { categoryId: "photographer", slug: "fotografos-brasileiros", label: "Fot\u00f3grafos brasileiros" },
  { categoryId: "performer", slug: "artistas-para-eventos-brasileiros", label: "Artistas para eventos brasileiros" },
  { categoryId: "food_truck", slug: "food-trucks-brasileiros", label: "Food trucks brasileiros" },
  { categoryId: "buffet", slug: "buffets-brasileiros", label: "Buffets brasileiros" },
  { categoryId: "doctor_female", slug: "medicas-brasileiras", label: "M\u00e9dicas brasileiras" },
  { categoryId: "depilation", slug: "depilacoes-brasileiras", label: "Depila\u00e7\u00f5es brasileiras" },
  { categoryId: "physiotherapy", slug: "fisioterapeutas-brasileiros", label: "Fisioterapeutas brasileiros" },
  { categoryId: "psychology", slug: "psicologos-brasileiros", label: "Psic\u00f3logos brasileiros" },
  { categoryId: "psychologist_female", slug: "psicologas-brasileiras", label: "Psic\u00f3logas brasileiras" },
  { categoryId: "nutrition", slug: "nutricionistas-brasileiros", label: "Nutricionistas brasileiros" },
  { categoryId: "hairdresser_female", slug: "cabeleireiras-brasileiras", label: "Cabeleireiras brasileiras" },
  { categoryId: "aesthetics", slug: "servicos-de-estetica-brasileiros", label: "Servi\u00e7os de est\u00e9tica brasileiros" },
  { categoryId: "general_contractor", slug: "empreiteiros-brasileiros", label: "Empreiteiros brasileiros" },
  { categoryId: "carpenter", slug: "marceneiros-brasileiros", label: "Marceneiros brasileiros" },
  { categoryId: "engineer", slug: "engenheiros-brasileiros", label: "Engenheiros brasileiros" },
  { categoryId: "architect", slug: "arquitetos-brasileiros", label: "Arquitetos brasileiros" },
  { categoryId: "gardener", slug: "jardineiros-brasileiros", label: "Jardineiros brasileiros" },
  { categoryId: "lawyer_female", slug: "advogadas-brasileiras", label: "Advogadas brasileiras" },
  { categoryId: "translator_female", slug: "tradutoras-brasileiras", label: "Tradutoras brasileiras" },
  { categoryId: "notary", slug: "notarios-brasileiros", label: "Not\u00e1rios brasileiros" },
  { categoryId: "notary_female", slug: "notarias-brasileiras", label: "Not\u00e1rias brasileiras" },
  { categoryId: "accountant_female", slug: "contadoras-brasileiras", label: "Contadoras brasileiras" },
  { categoryId: "financial_advisor_female", slug: "consultoras-financeiras-brasileiras", label: "Consultoras financeiras brasileiras" },
  { categoryId: "insurance_broker_female", slug: "corretoras-de-seguros-brasileiras", label: "Corretoras de seguros brasileiras" },
  { categoryId: "tax_preparation", slug: "imposto-de-renda", label: "Imposto de renda" },
  { categoryId: "teacher_female", slug: "professoras-brasileiras", label: "Professoras brasileiras" },
  { categoryId: "english_teacher_female", slug: "professoras-de-ingles-brasileiras", label: "Professoras de ingl\u00eas brasileiras" },
  { categoryId: "fashion", slug: "moda-brasileira", label: "Moda brasileira" },
  { categoryId: "beauty_store", slug: "produtos-de-beleza-brasileiros", label: "Produtos de beleza brasileiros" },
  { categoryId: "lingerie", slug: "roupas-intimas-brasileiras", label: "Roupas \u00edntimas brasileiras" },
  { categoryId: "furniture_store", slug: "decoracao-brasileira", label: "Decora\u00e7\u00e3o brasileira" },
  { categoryId: "gift_shop", slug: "lembrancas-brasileiras", label: "Lembran\u00e7as brasileiras" },
  { categoryId: "elderly_caregiver_female", slug: "cuidadoras-de-idosos-brasileiras", label: "Cuidadoras de idosos brasileiras" },
  { categoryId: "nurse_female", slug: "enfermeiras-brasileiras", label: "Enfermeiras brasileiras" },
  { categoryId: "commercial_cleaning", slug: "limpeza-comercial-brasileira", label: "Servi\u00e7os de limpeza comercial brasileiros" },
  { categoryId: "realtor_female", slug: "corretoras-de-imoveis-brasileiras", label: "Corretoras de im\u00f3veis brasileiras" },
  { categoryId: "mortgage_broker", slug: "financiamento-de-imoveis", label: "Consultoria de financiamento de im\u00f3veis" },
  { categoryId: "property_inspection", slug: "vistoria-de-imoveis", label: "Vistoria de im\u00f3veis" },
];
